apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
    - name: web-server
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: database
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysecretpassword
